# Generated by Django 4.0.3 on 2022-04-09 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yutorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='tutor',
            name='bio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutor',
            name='numRatings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('rating', models.FloatField()),
                ('numRatings', models.IntegerField()),
                ('bio', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('charge', models.FloatField()),
                ('duration', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('Tutee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yutorapp.tutee')),
                ('Tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yutorapp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start time')),
                ('end', models.DateTimeField(verbose_name='end time')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='yutorapp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='yutorapp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_link', models.URLField()),
                ('time_request', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('Tutee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yutorapp.tutee')),
                ('Tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yutorapp.tutor')),
            ],
        ),
    ]
