# Generated by Django 3.2 on 2022-04-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yutorapp', '0003_auto_20220409_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='yutorapp.tutor'),
        ),
    ]
