# Generated by Django 3.2 on 2022-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yutorapp', '0004_alter_timeslot_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
