# Generated by Django 4.0.3 on 2022-04-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yutorapp', '0006_alter_requesttimeslot_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tutee_done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='tutor_done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttimeslot',
            name='zoom_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('finished', 'Finished')], default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requesttimeslot',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='yutorapp.request'),
        ),
    ]
