# Generated by Django 4.0.3 on 2022-04-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yutorapp', '0007_request_tutee_done_request_tutor_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tutee_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='tutor_done',
            field=models.BooleanField(default=False),
        ),
    ]
