# Generated by Django 4.0.3 on 2022-04-10 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yutorapp', '0008_alter_request_tutee_done_alter_request_tutor_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, default='', max_length=400)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yutorapp.request')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='yutorapp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.FloatField()),
                ('requesttimeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yutorapp.requesttimeslot')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='yutorapp.tutor')),
            ],
        ),
        migrations.DeleteModel(
            name='TransactionTable',
        ),
    ]
