# Generated by Django 4.0.3 on 2022-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yutorapp', '0009_rating_transaction_delete_transactiontable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='rating',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
